apiVersion: v1
kind: Service
metadata:
  name: live-streaming-demo-frontend
spec:
  selector:
    app: live-streaming-demo
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-streaming-demo-frontend
  labels:
    app: live-streaming-demo
    tier: frontend
spec:
  selector:
    matchLabels:
      app: live-streaming-demo
      tier: frontend
  template:
    metadata:
      labels:
        app: live-streaming-demo
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: mattiacattarinussi/live-streaming-demo-frontend
          ports:
            - containerPort: 80
