apiVersion: v1
kind: Service
metadata:
  name: live-streaming-demo-redis
spec:
  selector:
    app: live-streaming-demo
    tier: cache
    component: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-streaming-demo-redis
  labels:
    app: live-streaming-demo
    tier: cache
    component: redis
spec:
  selector:
    matchLabels:
      app: live-streaming-demo
      tier: cache
      component: redis
  template:
    metadata:
      labels:
        app: live-streaming-demo
        tier: cache
        component: redis
    spec:
      containers:
        - name: redis
          image: redis:4-alpine
          ports:
            - containerPort: 6379
